name: 'Continuous Integration'
on: [ push, workflow_dispatch ]
jobs:
  continuousIntegration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Test Docker Image
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: |
            testDockerImage

      - name: Push Docker Image
        if: ${{ startsWith(github.ref, 'refs/heads/master') }}
        uses: gradle/gradle-build-action@v2
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          cache-read-only: false
          arguments: |
            pushDockerImage
